### ISSUE TITLE
签名串过期了？

### ISSUE THREAD

**Issue by johnson-gc** [pelucky/DouyuDanmu#2]

**Comment by pelucky** [comment]
有段时间没跑了，不确定斗鱼是否已经修改了这个值...

**Comment by johnson-gc** [comment]
后来试了可以，之前我别的步骤代码写错了。

**Comment by LuhxhuL** [comment]
> 后来试了可以，之前我别的步骤代码写错了。

兄弟 怎么可以得 你的VK 是怎么得出来的

**Comment by johnson-gc** [comment]
> > 后来试了可以，之前我别的步骤代码写错了。
> 
> 兄弟 怎么可以得 你的VK 是怎么得出来的

时间戳+7oE9nPEG9xXV69phU31FYCLUagKeYtsF+设备号，签名串还是文档里面那一串，逗鱼没变过

**Comment by pelucky** [comment]
那就好。。有空的时候我更新下文档和代码...感觉斗鱼没事应该也不会变...

> > > 后来试了可以，之前我别的步骤代码写错了。
> > 
> > 
> > 兄弟 怎么可以得 你的VK 是怎么得出来的
> 
> 时间戳+7oE9nPEG9xXV69phU31FYCLUagKeYtsF+设备号，签名串还是文档里面那一串，逗鱼没变过
