### ISSUE TITLE
怎么发送贵族弹幕和有颜色的弹幕

### ISSUE THREAD

**Issue by LuhxhuL** [pelucky/DouyuDanmu#3]
兄弟 问下你是用什么工具抓的包 我想抓包改一下

**Comment by pelucky** [comment]
贵族弹幕和有颜色的弹幕应该是需要用户开通对应的权限吧（我等穷屌丝从来没开过），然后抓包看下发弹幕的参数吧。
wireshark抓下通信包看下应该就可以。

**Comment by LuhxhuL** [comment]
好的 谢谢 哈哈哈 我昨天抓了一下  没抓到。。 感觉好像加密了
