### ISSUE TITLE
 Connect to Server 119.90.49.89:8092链接失败怎么办

### ISSUE THREAD

**Issue by lpomoeabatata** [pelucky/DouyuDanmu#4]

**Comment by cnchy** [comment]
改了吧 ，wsproxy.douyu.com:6673，验证协议为 ：
"type@=loginreq/roomid@=2561707/dfl@=sn@AA=105@ASss@AA=1/username@=sdadsda/password@=/ltkid@=***/biz@=1/stk@=***/devid@=b95c14c6362cc27a7188576d00021501/ct@=0/pt@=2/rt@=***/vk@=1989377f39fa69918f6f7c52ba23107a/ver@=20180222/aver@=218101901/"
发送弹幕 协议"content@=111111111/col@=0/type@=chatmessage/dy@=***/sender@=376763/ifs@=0/nc@=0/rev@=0/admzq@=0/cst@=1547137729931/"
里面的*** 替换自己de

**Comment by lpomoeabatata** [comment]
额不好意思我比较小白，具体改哪里啊？

**Comment by cnchy** [comment]
你去js打断点  搜索gatewayLogin这个方法      [参数截图](https://i.loli.net/2019/01/11/5c389c2a162c4.png)
[协议截图](https://i.loli.net/2019/01/11/5c389dbcd3aee.png)  
[验证wss截图](https://i.loli.net/2019/01/11/5c389e3d6dfac.png)
