### ISSUE TITLE
还在support这个repo吗？

### ISSUE THREAD

**Issue by consciousgaze** [pelucky/DouyuDanmu#5]
能讲解一下发弹幕的协议是什么样子的吗？我看好像用了两个socket。是不同的server吗？Auth server是怎么找到的啊。

**Comment by pelucky** [comment]
已经很久没有更新维护了。。

**Comment by pelucky** [comment]
之前是在知乎上找了些资料，抓包分析了解决的~

**Comment by consciousgaze** [comment]
我尝试用wireshark抓包。可是实在没有什么经验。没有用的包太多我找不到发弹幕的包。你还有兴趣再帮忙看一下吗？之前是怎么确定到发弹幕的包的？
